version: "3.7"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - C:\\Users\\georg\\PluralSight\\DockerSqlServer\\Database:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Croco*742"
      ACCEPT_EULA: "Y"